#+TITLE: Notes

* Convenience

Run the following script after putting in your user name

#+begin_src shell
for i in Desktop Documents Downloads Videos Music Pictures; do
  ln -s /mnt/c/Users/<username>/$i ~
done
#+end_src

* How to Mount Windows Network Drives in WSL

** Mount a Drive Until Logoff

1. Note the letter of the network drive that you would like to map in WSL. We will use M: in this example.
2. Create a new folder for that drive letter under /mnt if it does not already exist. (ex: ~mkdir /mnt/m~)
3. Mount the drive with ~sudo mount -t drvfs M: /mnt/m~


** Mount Drives in a Persistent Manner

1. Ensure the folder exists for the mount target (e.g. /mnt/m)
2. Open /etc/fstab and add a line such as the following:
   M: /mnt/m drvfs defaults 0 0
3. Reload the fstab file with ~sudo mount -a~

* How to Shrink a WSL2 Virtual Disk

** Before you begin

Before shrinking a WSL2 virtual disk, you need to ensure that WSL2 is not running.

You can check if it’s running with the command ~wsl.exe --list --verbose~ in PowerShell.
It should stop when it’s idle, or you can encourage it to stop with the ~wsl.exe --terminate~ command.

** Use ~diskpart~ to Shrink a WSL2 Virtual Disk

You can launch the ~diskpart~ tool in ~PowerShell~.

You need to specify the path to your VHDX file.
#+begin_src powershell
select vdisk file="C:\Users\valorin\AppData\Local\Packages\WhitewaterFoundryLtd.Co.16571368D6CFF_kd...\LocalState\ext4.vhdx"
#+end_src

Once it’s selected, you can ask ~diskpart~ to compact it:
#+begin_src powershell
compact vdisk
#+end_src

Once that has finished, you can close ~diskpart~.

* How to reduce the size of VMware disk

#+begin_src sh
sudo vmware-toolbox-cmd disk shrink /
#+end_src

* builds everything from source if Nix user isn't trusted
#+begin_quote
warning: ignoring untrusted substituter 'https://cachix.cachix.org'
#+end_quote

Workaround:
#+begin_src shell
echo "trusted-users = root $USER" | sudo tee -a /etc/nix/nix.conf"
sudo pkill nix-daemon
#+end_src

* Interview Questions to Ask Your Interviewer
How big is the company?

Why did you choose to work here?

Do you enjoy this particular project?

Is there flexibility within the org to move around to different projects?

What's a typical day like?


Software dev process? (agile/tdd/pairing?)

Bug tracking system?

Version control system?

Dev. desktop vs server OS? Developer machine hardware?


Is the product live in production? If not, what's the schedule for developing it?

How often are releases done?

Who supports the product once it's released? Pager duty? Monitoring email?

Where do feature + bugfix requests come from?

Who does the "design" of the product? Internal designers, devs, both?

Would my work be full-stack, or focused on backend/frontend?

How big is the code base? Lots of ties to external/legacy projects?


Typical working hours? Flexibility? Crunch times?

Working from home? Regularly vs. Snow days?


Do you have a favorite part of the job? Least favorite?

Do you have a time tracking system?

Centralized IT dept?

Gov’t contractor? Clearance required? Potential for clearance?

Regulatory compliance? PCI, SOX, etc. Annual training?


Do people hang out outside work? Company outings? Lunch?

Budget for conferences?

Internal lightning talks/brown bag lunches?

Dress code?


Does the company seem stable? Profitable? Any plans to sell?

Bonus structure?

Management style/structure? Frequent catch-ups aka one-on-ones? Something else?

Room for advancement?

Learning opportunities?
