-- Functional wrapper for mapping custom keybindings
function map(mode, lhs, rhs, opts)
    local options = { noremap = true }
    if opts then
        options = vim.tbl_extend("force", options, opts)
    end
    vim.api.nvim_set_keymap(mode, lhs, rhs, options)
end
vim.api.nvim_set_keymap("n", "j", "gj", {})
vim.api.nvim_set_keymap("n", "k", "gk", {})

-- Vim for Colemak
-- map('', 'n', 'j', {})
-- map('', 'e', 'k', {})
-- map('', 'i', 'l', {})
-- map('', 'j', 'e', {})
-- map('', 'k', 'n', {})
-- map('', 'l', 'i', {})
-- map('', 'K', 'N', {})
-- map('', 'N', '5j', {})
-- map('', 'E', '5k', {})
-- map('', 'L', 'I', {})

-- lower
-- map('', 'f', 'e', {})
-- map('', 'p', 'r', {})
-- map('', 'g', 't', {})
-- map('', 'j', 'y', {})
map('', 'l', 'u', {})
map('', 'u', 'i', {})
-- map('', 'y', 'o', {})
-- map('', 'o', ';', {})
-- map('', ';', 'p', {})
-- map('', 'r', 's', {})
-- map('', 's', 'd', {})
-- map('', 't', 'f', {})
-- map('', 'd', 'g', {})
map('', 'n', 'j', {})
map('', 'e', 'k', {})
map('', 'i', 'l', {})
-- map('', 'k', 'n', {})
-- map('', 'f', 'e', {})

-- upper
-- map('', 'P', 'R', {})
-- map('', 'G', 'T', {})
-- map('', 'J', 'Y', {})
map('', 'L', 'U', {})
map('', 'U', 'I', {})
-- map('', 'Y', 'O', {})
-- map('', ':', 'P', {})
-- map('', 'O', ':', {})
-- map('', 'R', 'S', {})
-- map('', 'S', 'D', {})
-- map('', 'T', 'F', {})
-- map('', 'D', 'G', {})
map('', 'N', 'J', {})
map('', 'E', 'K', {})
map('', 'I', 'L', {})
-- map('', 'K', 'N', {})
-- map('', 'F', 'E', {})
